# Generated by Django 3.1.2 on 2023-06-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('uname', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('rpassword', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('bio', models.CharField(default='I am a new user.', max_length=200)),
                ('portfolio_img', models.ImageField(blank=True, default='', null=True, upload_to='portfolio_images')),
                ('friends', models.ManyToManyField(blank=True, related_name='_userregister_friends_+', to='social.UserRegister')),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_time', models.TimeField(auto_now_add=True)),
                ('post_image', models.ImageField(blank=True, default='', null=True, upload_to='post_images')),
                ('post_video', models.FileField(blank=True, default='', null=True, upload_to='post_videos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('live', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('work', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('study', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ufrom', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.userregister')),
            ],
        ),
    ]
