# Generated by Django 3.1.2 on 2023-06-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='portfolio_img',
            field=models.ImageField(blank=True, default='/media/bg.jpg', null=True, upload_to='portfolio_images'),
        ),
    ]
