# Generated by Django 3.1.2 on 2023-06-13 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_followerscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='social.UserRegister')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.userregister')),
            ],
        ),
        migrations.DeleteModel(
            name='FollowersCount',
        ),
    ]
