# Generated by Django 3.1.2 on 2023-06-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20230614_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.userpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.userregister')),
            ],
        ),
    ]
