# Generated by Django 3.1.2 on 2023-06-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20230614_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.userregister'),
        ),
    ]
