# Generated by Django 3.1.2 on 2023-06-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20230615_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='bg_img',
            field=models.ImageField(blank=True, default='/media/bg.jpg', null=True, upload_to='bg_images'),
        ),
    ]
