# Generated by Django 3.1.2 on 2023-06-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20230616_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='bg_img',
            field=models.ImageField(blank=True, default='/media/bg_images/default_bg_img.jpg', null=True, upload_to='bg_images'),
        ),
    ]
