# Generated by Django 3.1.2 on 2023-06-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20230616_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='bg_img',
            field=models.ImageField(blank=True, default='default_bg_img.jpg', null=True, upload_to='bg_images'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='portfolio_img',
            field=models.ImageField(blank=True, default='default_pro_pic.jpeg', null=True, upload_to='portfolio_images'),
        ),
    ]
