# Generated by Django 3.1.2 on 2023-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_auto_20230616_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='portfolio_img',
            field=models.ImageField(default='default_pro_pic.jpg', upload_to='portfolio_images'),
        ),
    ]
